#if !canImport(ObjectiveC)
import XCTest

extension RuntimeTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RuntimeTest = [
        ("testTuna", testTuna),
        ("testOlives", testOlives),
        ("testCorn", testCorn),
    ]
}

extension RuntimeTestCaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RuntimeTestCaseTests = [
        ("test", test),
    ]
}

extension StandardTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StandardTest = [
        ("testMultipleIngredients", testMultipleIngredients),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RuntimeTest.__allTests__RuntimeTest),
        testCase(RuntimeTestCaseTests.__allTests__RuntimeTestCaseTests),
        testCase(StandardTest.__allTests__StandardTest),
    ]
}
#endif
